// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGuKkrZilyAYaqsdBXYagcGffp8Om1O8',
    appId: '1:962041178714:web:347cdb1f39624971ac4663',
    messagingSenderId: '962041178714',
    projectId: 'cpft-bf8a0',
    authDomain: 'cpft-bf8a0.firebaseapp.com',
    storageBucket: 'cpft-bf8a0.firebasestorage.app',
    measurementId: 'G-KQ010D0SFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8cJ9SwhG_hm0KfJkck1Puq13y3Ywq00',
    appId: '1:962041178714:android:720015f37599a0bbac4663',
    messagingSenderId: '962041178714',
    projectId: 'cpft-bf8a0',
    storageBucket: 'cpft-bf8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASrZpTaWvjTkvV69966UPlNxXCq9WJz0A',
    appId: '1:962041178714:ios:bda046e250af0e68ac4663',
    messagingSenderId: '962041178714',
    projectId: 'cpft-bf8a0',
    storageBucket: 'cpft-bf8a0.firebasestorage.app',
    iosBundleId: 'com.example.cpft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASrZpTaWvjTkvV69966UPlNxXCq9WJz0A',
    appId: '1:962041178714:ios:bda046e250af0e68ac4663',
    messagingSenderId: '962041178714',
    projectId: 'cpft-bf8a0',
    storageBucket: 'cpft-bf8a0.firebasestorage.app',
    iosBundleId: 'com.example.cpft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKGuKkrZilyAYaqsdBXYagcGffp8Om1O8',
    appId: '1:962041178714:web:db22eb94d9102b2dac4663',
    messagingSenderId: '962041178714',
    projectId: 'cpft-bf8a0',
    authDomain: 'cpft-bf8a0.firebaseapp.com',
    storageBucket: 'cpft-bf8a0.firebasestorage.app',
    measurementId: 'G-694KK3ZZBY',
  );
}
