source 'https://rubygems.org'

gem 'cocoapods', '>= 1.16.2'
# xcodeproj >= 1.28 adds support for Xcode project object version 70
# which fixes: "Unable to find compatibility version string for object version `70`"
gem 'xcodeproj', '>= 1.28.0'
